### ISSUE TITLE
Challenge Submission - watermaker with bitwis lest signifigent bit

### ISSUE THREAD

**Issue by Burnsedia** [pyatl/jam-sessions#15]
# Synopsis
incode name of the person who snapped a picture or makes a texture file with Krita or photoshop and uses a least significant bit

# Examples
input artist stage name output Unicode binary formate of the artist or company name in png or jpg file.

**Comment by xvillaneau** [comment]
So here's a few ideas, to help flesh this out.

It seems that what you describe is _Least Significant Bit Steganography_, which sounds like an interesting idea. I'm basing myself off this document for research:
https://www.boiteaklou.fr/Steganography-Least-Significant-Bit.html

### Beginner level (in cyber-dojo.org)

This is a simplified version of image steganography, where we're simply trying to put one message into a longer byte stream.

1. Write a function that can extract the LSB from a single byte (of type `(bytes,) -> int`; a bit could be equally represented with a `bool` but `int` is probably easier to grasp for beginners).
2. Use that code to write a function to extract a message from a sequence (of type `(bytes,) -> bytes`).
3. Write a function to overwrite the LSB of a byte (of type `(bytes, int) -> bytes`).
4. Use that code to write a function to insert a message into a byte stream (of type `(bytes, bytes) -> bytes`)
5. Optionally: add levels of encoding or encryption to the message

I feel like using `bytes` for both the data stream we're hiding and the background are important to understand what's going on, although it's at the cost of added complexity (and Python's built-in `int` / `bytes` / binary conversion tooling is a little unwieldy). The challenge will also be to handle problems such as:

- making sure the hidden stream is zero-padded on the MSB with `NULL` bytes, and ignore them (OR encode message length as well?).
- making sure the background byte stream is large enough (more than 8x larger than the message)

Just this will be a big challenge for newcomers. We'll need to make sure we provide a list of concepts to understand and good guidance. For example, here are a list of tips we could provide:

- how to convert `str` into `bytes`, and back,
- how to convert `bytes` into an integer and back, using `int.from_bytes` and `int.to_bytes`,
- how to extract the bits from an integer,
- how to convert a sequence of bits into an `int`.

### Advanced level

This could not be done in cyber-dojo.org since it will require additional libraries. The challenge would be to implement some kind of abstract base class(es?) that expand the idea to other data streams:

- hide a message in a `pillow` image or `numpy` array,
- hide an 1-bit deep image into another grayscale image.

This would be more open-ended, and could result in some kind of useable tool?

**Comment by xvillaneau** [comment]
@Burnsedia, do you want to work on fleshing this out, or would you like help with that?

**Comment by Burnsedia** [comment]
Sorry about the delay, working on some projects and I couldn't get my stuff working and just now I am pushing it to Github
I think that I could use some help, NumPy is not my area of expertise but not impossible for me to learn I am in more of the development mindset not so much of the sciences, I love science and ML but still learning the theoretical stuff.

**Comment by xvillaneau** [comment]
Sure, I can help.

In my mind the numpy part would be more of a do-it-yourself bonus in the exercise, for those who want to go further. And we can't do that on cyber-dojo anyway.

What really needs to be fleshed out is the beginners part. I'm starting to think that even manipulating `bytes` is somewhat complicated but could be appropriate for a second part. A first part could involve doing the process on a lists of integers. I can work on that.

**Comment by xvillaneau** [comment]
Wrote a first version of the challenge, but haven't opened a PR yet. Any feedback on it?
https://github.com/xvillaneau/jam-sessions/tree/jam_session_2019-10-03/2019-10

**Comment by Burnsedia** [comment]
that is great, I like it and even I can understand this. It is not what I was wanting to make but we could turn this into a great Plugin if we wanted to for all those FOSS art tools
